<?php

/**
 * PluginPerformanceObjectiveTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPerformanceObjectiveTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginPerformanceObjectiveTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginPerformanceObjective');
    }
}