<?php

/**
 * PluginPerformanceObjectiveReviewerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPerformanceObjectiveReviewerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginPerformanceObjectiveReviewerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginPerformanceObjectiveReviewer');
    }
}