<?php

/**
 * PluginPerformanceObjectiveReviewer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginPerformanceObjectiveReviewer extends BasePerformanceObjectiveReviewer
{

    const STATUS_ACTIVE = 1;
    const STATUS_DELETED = 2;
}