<?php

/**
 * PerformanceObjectiveTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PerformanceObjectiveTable extends PluginPerformanceObjectiveTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PerformanceObjectiveTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PerformanceObjective');
    }
}