<?php

/**
 *  UpskillsConfiguration class file
 */

/**
 * UpskillsConfiguration
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    orangehrm
 * @subpackage model\admin
 */
class UpskillsConfiguration extends PluginUpskillsConfiguration
{
}
