<?php

/**
 * PluginUpskillsConfiguration class file
 */

/**
 * PluginUpskillsConfiguration
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    orangehrm
 * @subpackage model\admin\plugin
 */
abstract class PluginUpskillsConfiguration extends BaseUpskillsConfiguration
{
	const	DEFAULT_UPSKILLS_CONFIGURATION_LENGTH = 8;
}