<?php

/**
 * PluginUpskillsConfigurationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginUpskillsConfigurationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginUpskillsConfigurationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginUpskillsConfiguration');
    }
}