<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2016/10/18 10:21:08

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;port=3306;dbname=hrupskills',
  'username' => 'root',
  'password' => 123456,
  'attributes' => 
  array (
    'export' => 'tables',
  ),
  'name' => 'doctrine',
)),);
