<?php

/**
 * BaseUpskillsConfiguration
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $value
 * @property string $comment
 * 
 * @method integer                 getId()                Returns the current record's "id" value
 * @method string                  getName()              Returns the current record's "name" value
 * @method string                  getValue()             Returns the current record's "value" value
 * @method string                  getComment()           Returns the current record's "comment" value
 * @method UpskillsConfiguration   setName()              Sets the current record's "name" value
 * @method UpskillsConfiguration   setValue()             Sets the current record's "value" value
 * @method UpskillsConfiguration   setComment()           Sets the current record's "comment" value

 * 
 * @package    orangehrm
 * @subpackage model\admin\base
 * @author     Marc Ghilardi
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUpskillsConfiguration extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_upskills_configuration');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 250, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 250,
             ));
        $this->hasColumn('value', 'string', 250, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 250,
             ));
        $this->hasColumn('comment', 'string', 250, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 250,
             ));
    }
}