<?php

/**
 * BasePerformanceObjectiveLog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $performance_objective_id
 * @property string $log
 * @property string $comment
 * @property integer $status
 * @property integer $achievement
 * @property timestamp $added_date
 * @property timestamp $modified_date
 * @property integer $reviewer_id
 * @property integer $user_id
 * @property PerformanceObjective $PerformanceObjective
 * @property Employee $Employee
 * @property SystemUser $SystemUser
 * @property decimal $rating
 * @property int $review_id
 * 
 * @method integer               getId()                   Returns the current record's "id" value
 * @method integer               getPerformanceObjectiveId()   Returns the current record's "performance_objective_id" value
 * @method string                getLog()                  Returns the current record's "log" value
 * @method string                getComment()              Returns the current record's "comment" value
 * @method integer               getStatus()               Returns the current record's "status" value
 * @method integer               getAchievement()          Returns the current record's "achievement" value
 * @method timestamp             getAddedDate()            Returns the current record's "added_date" value
 * @method timestamp             getModifiedDate()         Returns the current record's "modified_date" value
 * @method integer               getReviewerId()           Returns the current record's "reviewer_id" value
 * @method integer               getUserId()               Returns the current record's "user_id" value
 * @method PerformanceObjective      getPerformanceObjective()     Returns the current record's "PerformanceObjective" value
 * @method Employee              getEmployee()             Returns the current record's "Employee" value
 * @method SystemUser            getSystemUser()           Returns the current record's "SystemUser" value
 * @method decimal 				 getRating()			   Returns the current record's "rating" value
 * @method int 					 getReviewId()  		   Returns the current record's "review_id" value
 *
 * @method PerformanceObjectiveLog setId()                   Sets the current record's "id" value
 * @method PerformanceObjectiveLog setPerformanceObjectiveId()   Sets the current record's "performance_objective_id" value
 * @method PerformanceObjectiveLog setLog()                  Sets the current record's "log" value
 * @method PerformanceObjectiveLog setComment()              Sets the current record's "comment" value
 * @method PerformanceObjectiveLog setStatus()               Sets the current record's "status" value
 * @method PerformanceObjectiveLog setAchievement()          Sets the current record's "achievement" value
 * @method PerformanceObjectiveLog setAddedDate()            Sets the current record's "added_date" value
 * @method PerformanceObjectiveLog setModifiedDate()         Sets the current record's "modified_date" value
 * @method PerformanceObjectiveLog setReviewerId()           Sets the current record's "reviewer_id" value
 * @method PerformanceObjectiveLog setUserId()               Sets the current record's "user_id" value
 * @method PerformanceObjectiveLog setPerformanceObjective()     Sets the current record's "PerformanceObjective" value
 * @method PerformanceObjectiveLog setEmployee()             Sets the current record's "Employee" value
 * @method PerformanceObjectiveLog setSystemUser()           Sets the current record's "SystemUser" value
 * @method PerformanceObjectiveLog setRating()   			 Sets the current record's "rating" value
 * @method PerformanceObjectiveLog setReviewId() 			 Sets the current record's "review_id" value
 * 
 * @package    orangehrm
 * @subpackage model\performanceobjective\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePerformanceObjectiveLog extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_performance_objective_log');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('performance_objective_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('log', 'string', 500, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 500,
             ));
        $this->hasColumn('comment', 'string', 3000, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 3000,
             ));
        $this->hasColumn('status', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 2,
             ));
        $this->hasColumn('achievement', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 2,
             ));
        $this->hasColumn('added_date', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('modified_date', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('reviewer_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('user_id', 'integer', 10, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 10,
             ));
		$this->hasColumn('rating as rating', 'decimal', null, array(
             'type' => 'decimal',
			 'notnull' => false,
             ));
		$this->hasColumn('review_id', 'integer', 7, array(
			'type' => 'integer',
			'fixed' => 0,
			'notnull' => false,
			'autoincrement' => false,
			'length' => 7,
			));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PerformanceObjective', array(
             'local' => 'performance_objective_id',
             'foreign' => 'id'));

        $this->hasOne('Employee', array(
             'local' => 'reviewer_id',
             'foreign' => 'emp_number'));

        $this->hasOne('SystemUser', array(
             'local' => 'user_id',
             'foreign' => 'id'));
    }
}