<?php

/**
 * BasePerformanceObjectiveReviewer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $performance_objective_id
 * @property integer $reviewer_id
 * @property timestamp $added_date
 * @property integer $status
 * @property decimal $finalRate
 * @property clob $finalComment
 * @property PerformanceObjective $PerformanceObjective
 * @property Employee $Employee
 * 
 * @method integer                    getId()                   Returns the current record's "id" value
 * @method integer                    getPerformanceObjectiveId()   Returns the current record's "performance_objective_id" value
 * @method integer                    getReviewerId()           Returns the current record's "reviewer_id" value
 * @method timestamp                  getAddedDate()            Returns the current record's "added_date" value
 * @method integer                    getStatus()               Returns the current record's "status" value
 * @method decimal                    getFinalRate()            Returns the current record's "finalRate" value
 * @method clob                       getFinalComment()         Returns the current record's "finalComment" value
 * @method PerformanceObjective           getPerformanceObjective()     Returns the current record's "PerformanceObjective" value
 * @method Employee                   getEmployee()             Returns the current record's "Employee" value
 * @method PerformanceObjectiveReviewer setId()                   Sets the current record's "id" value
 * @method PerformanceObjectiveReviewer setPerformanceObjectiveId()   Sets the current record's "performance_objective_id" value
 * @method PerformanceObjectiveReviewer setReviewerId()           Sets the current record's "reviewer_id" value
 * @method PerformanceObjectiveReviewer setAddedDate()            Sets the current record's "added_date" value
 * @method PerformanceObjectiveReviewer setStatus()               Sets the current record's "status" value
 * @method PerformanceObjectiveReviewer setFinalRate()            Sets the current record's "finalRate" value
 * @method PerformanceObjectiveReviewer setFinalComment()         Sets the current record's "finalComment" value
 * @method PerformanceObjectiveReviewer setPerformanceObjective()     Sets the current record's "PerformanceObjective" value
 * @method PerformanceObjectiveReviewer setEmployee()             Sets the current record's "Employee" value
 * 
 * @package    orangehrm
 * @subpackage model\performanceobjective\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePerformanceObjectiveReviewer extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_performance_objective_reviewer');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('performance_objective_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('reviewer_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('added_date', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('status', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('final_comment as finalComment', 'clob', 65532, array(
            'type' => 'clob',
            'length' => 65532,
        ));
        $this->hasColumn('final_rate as finalRate', 'decimal', null, array(
            'type' => 'decimal',
        ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PerformanceObjective', array(
             'local' => 'performance_objective_id',
             'foreign' => 'id'));

        $this->hasOne('Employee', array(
             'local' => 'reviewer_id',
             'foreign' => 'emp_number'));
    }
}