<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2016/11/21 10:34:05

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;port=3306;dbname=ohm_vn',
  'username' => 'root',
  'password' => 123456,
  'attributes' => 
  array (
    'export' => 'tables',
  ),
  'name' => 'doctrine',
)),);
